name: My Frist Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Setup checkout
          uses: actions/checkout@v3
        
        - name: Welcome message
          run: |
            echo "My First github action"
            ls -all
            cat README.md
        
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "RUn for cover,I am a DRAGON" >> drgaon.txt   
        # - name: List files
        #   run: ls
        
        # - name: Read File
        #   run: cat README.md